### ISSUE TITLE
Output does not discriminate parent directory

### ISSUE THREAD

**Issue by hieudtn** [rdaneelu/checkgit#1]
Create 2 git directories with the same name. `repo` and `copy/repo`. 
The output be like
```
REPOSITORIES:
repo: ALL OK
repo: ALL OK
```
This might lead to confusion when I clone a certain repo and play with it, and then fork the repo for my own development.

**Comment by hieudtn** [comment]
I think it's a good idea to display the github username next to the repository name. Something like `rdaneelu/checkgit`

**Comment by hieudtn** [comment]
PR created https://github.com/rdaneelu/checkgit/pull/5

**Comment by rdaneelu** [comment]
Kind of fixed it. In the config file you have the option of adding a name starting with a '~' after the path.
path/to/repo1 --(as much space as you want)-- ~your_repo_name
path/to/repo2
if you don't give it a name it takes the name of the directory is in
if 2 or more repos are named exactly the first will not be touch but the other will have a number attached to them acording their position in the list
