### ISSUE TITLE
Use flags to add repositories

### ISSUE THREAD

**Issue by psyud** [rdaneelu/checkgit#2]
Manually appending to the config file seems like can be replaced by using a flag. `-a <dir>` for example.
Would like to create a PR for this.

**Comment by rdaneelu** [comment]
I barely know how to quit vim, I don't know if I'm able to do this one.

**Comment by hieudtn** [comment]
I can do that :)

**Comment by hieudtn** [comment]
:q to quit vim. :q! to force quit

**Comment by rdaneelu** [comment]
This issue will have to stay open for a while, but I'll try i'm interested

**Comment by rdaneelu** [comment]
found an excelent solution, I'll work on it and will soon have it running

**Comment by rdaneelu** [comment]
fixed. I took a different approach

**Comment by rdaneelu** [comment]
@psyud fixed, took a different approach.
