### ISSUE TITLE
Duplicated output when a git directory appear more than once in the config

### ISSUE THREAD

**Issue by hieudtn** [rdaneelu/checkgit#3]
Execute `pwd >> ~/.config/.checkgit` multiple times
`checkgit` output be like
```
REPOSITORIES:
gitdir: ALL OK
gitdir: ALL OK
gitdir: ALL OK
gitdir: ALL OK
```
Would like to create a PR for this

**Comment by hieudtn** [comment]
PR created https://github.com/rdaneelu/checkgit/pull/4

**Comment by rdaneelu** [comment]
Fixed! now it ignores duplicated paths in config file. And if a name is given to 2 or more different paths it gives a number at the end.
REPOSITORIES:
gitdir: ALL OK
gitdir2: ALL OK
gitdir3: ALL OK
